[package]
name = "clash-roam"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
lto = true

[dependencies]
futures = "0.3"
tokio = { version = "1.33", features = ["rt", "macros"] }
reqwest = { version = "0.12", default-features = false, features = ["json"] }
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
pretty_env_logger = { git = "https://github.com/karin0/pretty-env-logger.git" }
ip-roam = { git = "https://github.com/karin0/ip-roam.git" }
